### ISSUE TITLE
After pickup cached IP adding " " to ip

### ISSUE THREAD

**Issue by ntrx** [ntrx/Firmware-Works#16]
After pickup cached IP adding " " to ip and can't ping

Ping request could not find host 192.168.9.177
. Please check the name and try again.

**Comment by bigsbug** [comment]
hi can I doing this ?
please give me address file and function

**Comment by ntrx** [comment]
@bigsbug You are not participate in developing this app

**Comment by ntrx** [comment]
Fixed by added check_value function to IP string from combobox
